### ISSUE TITLE
Passing options or config overrides?

### ISSUE THREAD

**Issue by squarism** [nats-io/nats-docker#1]
Trying to set some options on `docker run`, just to have a feeling of control of options like the password.  Tried a few variations like this:

`docker run --rm -p 8222:8222 -p 6222:6222 -p 4222:4222 --name nats-main nats nats --pass=asdf`

And then running the second node, but I get authorization errors because I'm doing something wrong here. I see in the docker hub README, you can pass `--routes` like this but can you not pass other flags too?  Is there a better way, like can I have a local `.conf` file (on my docker host) and pass it in somehow to `-c`?  That seems impossible from what I know with docker, just wondering how the `docker run` example would look if you want to use a conf file.

Thanks for making a docker image regardless!  Was really nice to have this.

**Comment by derekcollison** [comment]
Yes you should be able to pass flags and override what is in the configuration file.

**Comment by kozlovic** [comment]
@squarism You can pass command line parameters to gnatsd. PR #4 has been merged helps with that too.
