### ISSUE TITLE
supprot arm64 architecture

### ISSUE THREAD

**Issue by longquan7** [nats-io/nats-docker#10]
I was used this Dockerfile to build on arm64 system,and  it's successed.so I think we can pull it to https://hub.docker.com/u/arm64v8/

**Comment by longquan7** [comment]
I wonder if you are supportive this image for arm64 architecture

**Comment by kozlovic** [comment]
I believe that arm64 is not officially supported by Docker, so I am not sure if we will provide an image for that at this time: https://github.com/docker-library/official-images#architectures-other-than-amd64. We need to discuss this more internally.

**Comment by longquan7** [comment]
@kozlovic Please let me know if you support arm64,thanks

**Comment by kozlovic** [comment]
We do not build an executable for arm64 so far. I have also tried to cross compile it for this platform and make a docker image with this executable, either from `scratch` or from `arm64v8/golang:1.8-alpine` and in both cases I am unable to run the image. I get different errors depending if I run from Mac OS or from a Linux VM (Virtual Box). So it would be difficult to support something that we can not even run ourselves.

**Comment by longquan7** [comment]
@kozlovic ok,thank

**Comment by kozlovic** [comment]
@longquan7 Out of curiosity, how did you verify that it was working? Did you compile on a arm64 platform or used cross compile, and then, on which platform did you build the image (and did you build the image from `scratch` or another image)? Thanks!

**Comment by longquan7** [comment]
@kozlovic I was just build it on arm64 platform,but the file gnatsd is come from x86 platfrom, So I want to konw that gnatsd whether or not support arm64.

**Comment by kozlovic** [comment]
@longquan7 I have merged PR #11 that will allow us to produce docker images for ARM architectures. However, these images won't be avail until we issue a new NATS Server release, likely 1.0.4. We should be doing that very soon.

**Comment by longquan7** [comment]
@kozlovic OK ,thanks

**Comment by alexellis** [comment]
Hey, was speaking to Brian the community manager at NATS. Would be great to have ARMv7 support too. I'm working on something to show NATS Streaming on a small form factor device and an official image would help hugely. Arm is already a build target.

**Comment by kozlovic** [comment]
@alexellis You mean support for ARMv7 and docker image for NATS Streaming, right? It was planned to do that too since we are doing it for NATS Server.
