### ISSUE TITLE
Timezone setting support

### ISSUE THREAD

**Issue by damir-ope** [nats-io/nats-docker#112]
Hello,

Nats image does not support setting of the timezone.

Similar issue raised 4 years ago:
Linked issue:
https://github.com/nats-io/nats-docker/issues/17

Nats is using latest(3.18) alpine version which does not contain `tzdata` package.
Alpine removed that package with one of the releases.

Can you please add that package in Dockerfile?

Thanks,
Damir

**Comment by bruth** [comment]
@damir-ope Thanks for the report! Any idea when Alpine removed it? I opened a PR to add it explicitly.

**Comment by damir-ope** [comment]
> Any idea when Alpine removed it?

Thanks @bruth for quick reply.

Tried to find that info on the release note page of alpine linux - nothing useful there.

Based on this comment seems it's been a while since it was removed:
https://github.com/dotnet/dotnet-docker/issues/1366
