### ISSUE TITLE
Add multiarch support for nats

### ISSUE THREAD

**Issue by vielmetti** [nats-io/nats-docker#12]
What I saw:

```
$ docker run --rm mplatform/mquery nats:latest
Manifest List: Yes
Supported platforms:
 - amd64/linux
```

What I expected to see:

Multiarch support for nats, with all supported platforms in the manifest.

**Comment by kozlovic** [comment]
@vielmetti We are adding ARM support on the next release (1.0.4, which we should release this week). However, not sure about the above list since we already have Windows (nanoserver and windowsservercore) support, and yet they don't show up in the list. So adding ARM support the way we intend to do (https://github.com/docker-library/official-images#multiple-architectures) may not be equivalent to multiarch support?

**Comment by vielmetti** [comment]
@kozlovic - at least until Docker finishes up a `docker manifest` command, the way that people are building multiarch images is with https://github.com/estesp/manifest-tool . I know that @estesp and @tianon has done a lot with this work, and the process is not too cumbersome.

**Comment by kozlovic** [comment]
The manifest is very recent and to be honest I don't think we will do that for the next release. There will be ARM images, but they will likely be prefixed with the platform. We will look into manifest for future releases.

**Comment by vielmetti** [comment]
Thanks @kozlovic that makes sense - by the time the following release rolls around the tooling should be better integrated and better understood.

**Comment by tianon** [comment]
@kozlovic if you implement what's described in https://github.com/docker-library/official-images#multiple-architectures for ARM, they'll show up in `manifest-tool inspect nats` :+1:

If you'd like to also add Windows to that list, you'll want to take advantage of `SharedTags`; see https://github.com/docker-library/official-images/blob/c41f1745ecdaeda7269faf57dff714a3e0609e1e/library/hello-world#L27 for an example of that which is probably fairly similar to NATS.

**Comment by kozlovic** [comment]
@tianon Fantastic! Yes, I will certainly do that. A release will all these changes is coming up this week. Stay tuned ;-)

**Comment by kozlovic** [comment]
@vielmetti The v1.0.4 is out and the command you mentioned will now print:
```
Manifest List: Yes
Supported platforms:
 - amd64/linux
 - arm/linux (variant: v7)
 - arm64/linux (variant: v8)
 - amd64/windows
```
Thanks again to @tianon for the help in making sure that the supported platforms show up properly!
