### ISSUE TITLE
Add support for the s390x architecture

### ISSUE THREAD

**Issue by jefflin0322** [nats-io/nats-docker#131]
Hi there,

There is no docker image that support for s390x architecture in the dockerhub.
So my question is why is not being generated this architecture ?
Please can you start to generate ?

Thanks in advance

**Comment by bruth** [comment]
Hey @jefflin0322. Good suggestion. This should be a straightforward addition.

**Comment by bruth** [comment]
The next release will have this build as a Docker image.
