### ISSUE TITLE
Add Windows Server 2019 variant

### ISSUE THREAD

**Issue by sixeyed** [nats-io/nats-docker#19]
The current official images only run on Windows Server 2016 - to run on the latest version of Windows Server, a new image will be needed that is based on Nano Server 1809. [Here is a simple example](https://github.com/sixeyed/docker-windows-workshop/blob/master/docker/backend-async-messaging/message-queue/Dockerfile).

**Comment by kozlovic** [comment]
Hey @sixeyed, nice to hear from you. So if I understand correctly, the link you posted is you building your own image taking the latest NATS release for nanoserver, right? So if we were to provide an official build we would have to add a new directory in this repo, say `nanoserver2019` and our Docker file would be similar to existing one but simply with the top-level FROM being different. Something like:
```
FROM mcr.microsoft.com/windows/nanoserver:1809

# The NAT Server will look for this environment variable.
# When set, it prevents the use of the service API to detect
# if it is running in interactive mode or not, which is
# failing in the context of a Docker container.
# (https://github.com/nats-io/gnatsd/issues/543)
ENV NATS_DOCKERIZED=1

WORKDIR c:/nats-server
COPY nats-server.exe nats-server.exe
COPY nats-server.conf nats-server.conf

# Expose client, management, and cluster ports
EXPOSE 4222 8222 6222

ENTRYPOINT ["nats-server"]
CMD ["-c", "nats-server.conf"]
```
Is that correct?

**Comment by kozlovic** [comment]
The other thing is that I am not sure we will be able to provide this as an official image because I am not sure Docker will accept a `FROM` other than `FROM microsoft/nanoserver`.

(I have tried to test building the image with the FROM you posted, but it fails for me, probably because I am running with a Windows 2016 Server VM image, so that's something also that I would not be able to verify if it works or not).

**Comment by sixeyed** [comment]
Your Dockerfile looks fine but yes, you'll need a Windows Server 2019 image to build from - AppVeyor have a 2019 builder for CI that you could try, or I'm happy to manually build for you :) 

The new [Nano Server](https://hub.docker.com/_/microsoft-windows-nanoserver) image has been flagged as "official", even though it's now served by Microsoft's MCR registry, so that shouldn't be a problem - the official OpenJDK image has a [Windows Server Core 2019 variant](https://hub.docker.com/_/microsoft-windows-nanoserver), and hello-world has a [Nano Server 1809 variant](https://github.com/docker-library/hello-world/blob/master/amd64/hello-world/nanoserver-1809/Dockerfile).

Those repos have some sample folder structures which would make the move to multi-arch easier too (if you're considering adding ARM support).

**Comment by kozlovic** [comment]
Closing, should be available now
