### ISSUE TITLE
Current version of nats:latest does not PING to client

### ISSUE THREAD

**Issue by mikunalpha** [nats-io/nats-docker#7]
Latest gnatsd does not have this problem.
Could you upgrade the gnatsd of this docker images on dockehub?

Thanks :D

**Comment by kozlovic** [comment]
Will do this early this week, stay tuned...

**Comment by kozlovic** [comment]
NATS Server 1.0.0 (with said fix) is now available for download. Thanks!

**Comment by mikunalpha** [comment]
Thank you :smile:
