### ISSUE TITLE
Stop using deprecated Windows 2016 hosted runners

### ISSUE THREAD

**Issue by philpennock** [nats-io/nats-docker#73]
Per email from GitHub:

> On March 15, 2022, Windows 2016 hosted runners will be [removed from GitHub Actions](https://github.blog/changelog/2021-10-19-github-actions-the-windows-2016-runner-image-will-be-removed-from-github-hosted-runners-on-march-15-2022/).
> 
> In preparation for the deprecation, there are two scheduled brownout periods for our team to perform maintenance:
>   * December 1, 2021: 4:00pm–10:00pm UTC
>   * February 7, 2022: 4:00pm–10:00pm UTC
> 
> Jobs that use Windows 2016 scheduled to run during this time will temporarily fail.
> 
> **What you need to do**
> We recommend you change jobs using `runs-on: windows-2016` to use `runs-on: windows-latest`  which will ensure you're always running on the latest version of Windows Server.

File `.github/workflows/main.yaml` defines a Job `windows-2016` which is `runs-on: windows-2016`.

**Comment by variadico** [comment]
From the release page:
https://docs.microsoft.com/en-us/windows-server/get-started/windows-server-release-info
```
Mainstream support end date: 2022-01-11    <-- very soon
Extended support end date: 2027-01-11
```

We have 1 Windows Server 2016 Docker image: https://github.com/nats-io/nats-docker/blob/main/2.6.5/windowsservercore-ltsc2016/Dockerfile

I updated our workflow file to run on `windows-2019` and got this error during image build.
```
---> Running in 84c70eb364fd
... The container operating system does not match the host operating system.
```
https://github.com/nats-io/nats-docker/runs/4375199705?check_suite_focus=true

Should we continue supporting Windows 2016? For publishing to Docker, we just send them a git hash. But, not being able to test if our images build is not good. We may have to switch to a different CI if this is something we want to continue supporting.

cc @kozlovic

**Comment by kozlovic** [comment]
Missed that one. Closing because we have removed win 2016 since v2.7.0 (https://github.com/nats-io/nats-docker/pull/75)
