### ISSUE TITLE
exec docker container error

### ISSUE THREAD

**Issue by yzcyayaya** [nats-io/nats-docker#92]
exec docker containerd error
```bash
$docker exec -ti docker-compose-nats-1 /bin/bash
OCI runtime exec failed: exec failed: unable to start container process: exec: "/bin/bash": stat /bin/bash: no such file or directory: unknown
$ docker exec -ti docker-compose-nats-1 /bin/sh
OCI runtime exec failed: exec failed: unable to start container process: exec: "/bin/sh": stat /bin/sh: no such file or directory: unknown
```
I want to go into the container

**Comment by ripienaar** [comment]
Suggest you use one of the alpine based containers instead to achieve that.

**Comment by kozlovic** [comment]
@yzcyayaya As @ripienaar suggested, you need to use the alpine image for that (and it is `/bin/sh`, not `/bin/bash`). The default `nats` image is from `SCRATCH` and does not have any shell.
