### ISSUE TITLE
2.9.6 tag not available on Docker Hub

### ISSUE THREAD

**Issue by tamalsaha** [nats-io/nats-docker#96]
https://hub.docker.com/_/nats/tags?page=1&name=2.9.6

**Comment by wallyqs** [comment]
It takes a bit for they to appear (part of this process: https://github.com/docker-library/official-images/pull/13479#event-7744255395) , seems it is up now: https://hub.docker.com/layers/library/nats/2.9.6/images/sha256-b7d7f838330af8f53d3bcfd355ab7ae938e994fe6ef1b9c4d715e41da214b9f2?context=explore
